jwt:
  secret: 'secretsecretsecretsecretsecretsecretsecretsecretsecretsecret'

server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database2
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
